name: multimedia-server
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
    volumes:
      - ./homepage:/app/config 
    restart: always

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./jellyfin:/config
      - F:/jellyfin:/media
    ports:
      - 8096:8096
    restart: always

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr:/app/config
    restart: always

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - F:/torrent-downloads:/downloads
    ports:
      - 8080:8080
    # network_mode: service:cloudflare
    restart: always
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: always

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./sonarr:/config
      - F:/jellyfin/tv:/tv
      - F:/torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./radarr:/config
      - F:/jellyfin/movies:/movies
      - F:/torrent-downloads:/downloads
    ports:
      - 7878:7878
    restart: always
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./bazarr:/config
      - F:/jellyfin/movies:/movies #optional
      - F:/jellyfin/tv:/tv #optional
    ports:
      - 6767:6767
    restart: always

